### ISSUE TITLE
FIRRTL Internal Error

### ISSUE THREAD

**Issue by s1104439112** [ucb-bar/project-template#60]
i got FIRRTL  ERROR when i try "make CONFIG=PWMConfig"

java -Xmx8G -Xss8M -cp "/mnt/e/Project/project-template/rocket-chip/target/scala-2.12/classes:/mnt/e/Project/project-template/rocket-chip/chisel3/target/scala-2.12/*":"/mnt/e/Project/project-template/testchipip/target/scala-2.12/classes":/mnt/e/Project/project-template/barstools/tapeout/target/scala-2.12/tapeout-assembly-1.0.jar barstools.tapeout.transforms.GenerateTop -o /mnt/e/Project/project-template/verisim/generated-src/example.TestHarness.PWMConfig.top.v -i /mnt/e/Project/project-template/verisim/generated-src/example.TestHarness.PWMConfig.fir --syn-top ExampleTop --harness-top TestHarness -faf /mnt/e/Project/project-template/verisim/generated-src/example.TestHarness.PWMConfig.anno.json --repl-seq-mem -c:TestHarness:-o:/mnt/e/Project/project-template/verisim/generated-src/example.TestHarness.PWMConfig.mems.conf -td /mnt/e/Project/project-template/verisim/generated-src
Exception in thread "main" firrtl.FIRRTLException: Internal Error! Please file an issue at https://github.com/ucb-bar/firrtl/issues
	at firrtl.Utils$.error(Utils.scala:440)
	at firrtl.Utils$.throwInternalError(Utils.scala:181)
	at firrtl.Driver$.$anonfun$execute$1(Driver.scala:252)
	at logger.Logger$.$anonfun$makeScope$2(Logger.scala:138)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at logger.Logger$.makeScope(Logger.scala:136)
	at firrtl.Driver$.execute(Driver.scala:224)
	at barstools.tapeout.transforms.GenerateTopAndHarnessApp.executeTop(Generate.scala:102)
	at barstools.tapeout.transforms.GenerateTopAndHarnessApp.executeTop$(Generate.scala:96)
	at barstools.tapeout.transforms.GenerateTop$.executeTop(Generate.scala:116)
	at barstools.tapeout.transforms.GenerateTop$.delayedEndpoint$barstools$tapeout$transforms$GenerateTop$1(Generate.scala:118)
	at barstools.tapeout.transforms.GenerateTop$delayedInit$body.apply(Generate.scala:116)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at barstools.tapeout.transforms.GenerateTop$.main(Generate.scala:116)
	at barstools.tapeout.transforms.GenerateTop.main(Generate.scala)
Caused by: java.util.NoSuchElementException: key not found: ExampleTop
	at scala.collection.MapLike.default(MapLike.scala:232)
	at scala.collection.MapLike.default$(MapLike.scala:231)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike.apply(MapLike.scala:141)
	at scala.collection.MapLike.apply$(MapLike.scala:140)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at barstools.tapeout.transforms.RemoveUnusedModules.execute(RemoveUnusedModules.scala:46)
	at firrtl.Transform.$anonfun$runTransform$2(Compiler.scala:199)
	at firrtl.Utils$.time(Utils.scala:186)
	at firrtl.Transform.runTransform(Compiler.scala:199)
	at firrtl.Compiler.$anonfun$compile$2(Compiler.scala:443)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at firrtl.Compiler.$anonfun$compile$1(Compiler.scala:443)
	at firrtl.Utils$.time(Utils.scala:186)
	at firrtl.Compiler.compile(Compiler.scala:443)
	at firrtl.Compiler.compile$(Compiler.scala:439)
	at firrtl.VerilogCompiler.compile(LoweringCompilers.scala:162)
	at firrtl.Driver$.$anonfun$execute$1(Driver.scala:242)
	... 18 more
/mnt/e/Project/project-template/Makefrag:65: recipe for target '/mnt/e/Project/project-template/verisim/generated-src/example.TestHarness.PWMConfig.top.v' failed
make: *** [/mnt/e/Project/project-template/verisim/generated-src/example.TestHarness.PWMConfig.top.v] Error 1

**Comment by s1104439112** [comment]
but I can use run "make CONFIG=RoccExampleConfig debug", get simulator-RoccExampleConfig.

**Comment by colinschmidt** [comment]
You need to set the `TOP` to the top-level module/dut's class name.
https://github.com/ucb-bar/project-template/blob/master/verisim/Makefile#L9

**Comment by s1104439112** [comment]
Thanks a lot, I will try it. ヽ(✿ﾟ▽ﾟ)ノ
